[package]
name = "test_8-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test_8-3-lib = { path = "../test_8-3-lib" }